### PR TITLE
Replace sass-lint with stylelint

### LINKED ISSUE #41: Replace sass-lint with stylelint
In a previous [dev catchup](https://github.com/canonical-web-and-design/meeting-notes/issues/477) it was decided that our projects should be updated to use [stylelint](https://stylelint.io/) instead of sass-lint which we are currently using.

### PR DESCRIPTION
**Pull request by steverydz**
## Done

Replaces sass-lint with stylelint and fixed resulting linting errors

## QA

- Check out this feature branch
- Run `./run exec yarn lint-scss`
- Check that there are no linting errors

## Issue / Card

Fixes #41

### CODE REVIEW

**Comment by nottrobin** [comment]
Would you mind also adding a CI check for this? https://github.com/canonical-web-and-design/charmed-osm.com/blob/master/.circleci/config.yml#L52

If you'd rather treat that as out-of-scope for this PR, that's fine too, but this project really should have CI checks and so if you don't mind adding them here it would be awesome.

**Comment by steverydz** [comment]
@nottrobin that makes sense - I'll add it as part of these tasks

**Comment by nottrobin** [comment]
@steverydz ah wait - could you add them as GitHub actions? It just means you have to create this branch on the upstream repo rather than your fork. I'll try to find you an example.

**Comment by steverydz** [comment]
@nottrobin this project already has a `lint-scss` CI check https://github.com/canonical-web-and-design/dqlite.io/blob/master/.circleci/config.yml#L35

**Comment by nottrobin** [comment]
@steverydz oh! OK I just turned on this project in circleci.com, could you please add a commit or something to trigger builds?

**Comment by nottrobin** [comment]
@steverydz Only the "test-site" action failed - I suspect this just needs a longer sleep time. Try `3`, and then `5` if that still doesn't work?

https://github.com/canonical-web-and-design/dqlite.io/blob/master/.circleci/config.yml#L24

**Pull request merged**
