### PR TITLE
Revert "Update Discourse module"

### PR DESCRIPTION
**Pull request by anthonydillon**
Reverts canonical-web-and-design/dqlite.io#92

### CODE REVIEW

**Comment by anthonydillon** [comment]
A fresh release resolved the issue in production.

**Comment by nottrobin** [comment]
Do we know that it's `3.0.1` and not `3.0.0` that introduced this issue?

**Comment by carkod** [comment]
The demo seems to be returning 500

**Comment by jkfran** [comment]
I think we can close this PR as it is not related with the issue. The issue seems to be with the warning headers this module add to the reponses.

> A fresh release resolved the issue in production.

Make sense because the response headers get bigger after a while, I redeployed and https://dqlite.io/docs is working now. I am working on a permanent fix.

**Comment by anthonydillon** [comment]
Yeah sorry this was a test to see if it solved the issue.

**Pull request closed without merging**
